version: '3.5'
services:
  db_postgres:
    image: postgres:latest
    restart: always
    container_name: 'db_postgres'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=__password__
      - POSTGRES_USER=__username__
